# Project
#github:
#  repo: https://github.com/org/repo
#  branch: main
#docsearch:
#  enabled: true
#  apiKey: xxxx
#  appId: xxxx
#  indexName: xxxx
#  debug: false
#sidebar:
#  - Group 1
#  - Group 2
manifest:
  background_color: '#EEF6FF'
  theme_color: '#1C4ED8'

# statidocs
pagination:
  enabled: false
pages:
  sortby: weight
  body:
    highlight:
      enabled: true
    images:
      resize:
        enabled: true
      webp:
        enabled: true
      responsive:
        enabled: true
      caption:
        enabled: true
    links:
      embed:
        enabled: true
