title: Statidocs
baseline: 'An effective documentation'
baseurl: 'https://cecilapp.github.io/statidocs/'
canonicalurl: true
description: 'Create and manage an effective documentation.'
author:
  name: 'Arnaud Ligny'
  url: 'https://arnaudligny.fr'
image: cecil-card.png
language: en
languages:
  - code: en
    name: English
    locale: en
  - code: fr
    name: Français
    locale: fr
theme:
  - docs
github:
  repo: https://github.com/Cecilapp/statidocs
  branch: main
docsearch:
  enabled: true
  apiKey: 'xxxx'
  appId: 'xxxx'
  indexName: 'xxxx'
sidebar:
  - Group 1
  - Group 2
  - Group 3
