title: Statidocs
baseline: 'An effective documentation'
baseurl: 'https://cecilapp.github.io/statidocs/'
canonicalurl: true
description: 'Create and manage an effective documentation.'
author:
  name: 'Arnaud Ligny'
  url: 'https://arnaudligny.fr'
image: cecil-card.png
theme:
  - docs
github:
  repo: https://github.com/Cecilapp/statidocs
sidebar:
  - Category 1
  - Category 2
  - Category 3
language: en
languages:
  - code: en
    name: English
    locale: en
  - code: fr
    name: Français
    locale: fr
